name: Build & Push ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build JAR by Gradle
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # 5. Login ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 6. Build & Push Docker
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO }}:latest

          docker build -t ${{ vars.ECR_REPO }} .
          docker tag ${{ vars.ECR_REPO }}:latest $IMAGE_URI
          docker push $IMAGE_URI
      # 7. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}

          script: |
            IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO }}:latest
            # Login ECR
            aws ecr get-login-password --region ${{ vars.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
            # Pull image
            docker pull $IMAGE_URI
            # Stop old container
            docker stop tl04 || true
            docker rm tl04 || true
            # Run new container with DB ENV
            docker run -d \
              --name tl04 \
              -p 3000:3000 \
              --restart always \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e DB_USER='${{ secrets.DB_USER }}' \
              -e DB_PASS='${{ secrets.DB_PASS }}' \
              $IMAGE_URI
