name: Build & Push ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login AWS báº±ng OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # 3. Login ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build + Push Docker Image
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO }}:latest

          echo "Build image..."
          docker build -t ${{ vars.ECR_REPO }} .

          echo "Tag image..."
          docker tag ${{ vars.ECR_REPO }}:latest $IMAGE_URI

          echo "Push image..."
          docker push $IMAGE_URI

          echo "Done: $IMAGE_URI"
